name: Trial Build

on: [push, pull_request]

jobs:
  compile:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 1.8, 11 ]
    name: Java ${{ matrix.java }} compile
    steps:
      - uses: actions/checkout@master
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - run: mvn -f pom.xml clean compile     
  build:
    runs-on: ubuntu-latest
    needs: compile
    name: Build do projeto maven
    steps:
    - uses: actions/checkout@v1
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build e test do projeto
      run: mvn -f pom.xml clean verify
    - name: Atualização das dependências
      uses: actions/upload-artifact@v1
      with:
        name: artifact
        path: ExemploParaIntegracaoContinua/target/exemplo-1.0.0.jar
